[profile.default]
src = "contracts"
out = "out"
libs = ["/Users/moueshouta/development/Blockchain/job/defi-erc4626-hardhat/node_modules", "lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/"
    ]
